export const MARKET_CONFIG = {
  REFRESH_INTERVAL_MS: 1000 * 60 * 10, // 10 minutes
  CACHE_KEY: "stockpile-market-cache-v3",
  MAX_RETRIES: 3,
};

export const SYMBOLS = [
  "NVDA", "AAPL", "MSFT", "GOOGL", "META", "TSLA", "AMZN", "AMD", "AVGO", "PLTR",
  "JPM", "BRK.B", "V", "MA", "UNH", "XOM", "LLY", "COIN", "SHOP", "SNOW",
  "NFLX", "CRM", "ADBE", "CSCO", "INTC", "QCOM", "TXN", "IBM", "ORCL", "NOW",
  "INTU", "UBER", "ABNB", "PYPL", "SQ", "ROKU", "ZM", "DOCU", "CRWD", "DDOG",
  "NET", "MDB", "PANW", "ZS", "FTNT", "OKTA", "TEAM", "WDAY", "SPLK", "VEEV",
  "WMT", "TGT", "COST", "HD", "MCD", "SBUX", "NKE", "DIS", "CMCSA", "PEP",
  "KO", "PG", "JNJ", "PFE", "MRK", "ABBV", "TMO", "DHR", "MDT", "SYK",
  "CVX", "COP", "SLB", "EOG", "PXD", "OXY", "MPC", "VLO", "PSX", "KMI",
  "BTC/USD", "ETH/USD", "SOL/USD", "ADA/USD", "DOGE/USD", "DOT/USD", "AVAX/USD", "MATIC/USD", "LINK/USD", "UNI/USD",
  "SPY", "QQQ", "GLD", "TLT", "IWM", "DIA", "VTI", "VOO", "ARKK", "SMH"
];

export const METADATA: Record<string, { name: string; sector: string; assetClass: string }> = {
  NVDA: { name: "NVIDIA Corp.", sector: "Semiconductors", assetClass: "Equities" },
  AAPL: { name: "Apple Inc.", sector: "Consumer Tech", assetClass: "Equities" },
  MSFT: { name: "Microsoft Corp.", sector: "Software", assetClass: "Equities" },
  GOOGL: { name: "Alphabet Inc.", sector: "Internet", assetClass: "Equities" },
  META: { name: "Meta Platforms", sector: "Social", assetClass: "Equities" },
  TSLA: { name: "Tesla Inc.", sector: "EV", assetClass: "Equities" },
  AMZN: { name: "Amazon.com", sector: "E-commerce", assetClass: "Equities" },
  AMD: { name: "Advanced Micro", sector: "Semiconductors", assetClass: "Equities" },
  AVGO: { name: "Broadcom Inc.", sector: "Semiconductors", assetClass: "Equities" },
  PLTR: { name: "Palantir Tech", sector: "Software", assetClass: "Equities" },
  JPM: { name: "JPMorgan Chase", sector: "Banking", assetClass: "Equities" },
  "BRK.B": { name: "Berkshire Hathaway", sector: "Conglomerate", assetClass: "Equities" },
  V: { name: "Visa Inc.", sector: "Payments", assetClass: "Equities" },
  MA: { name: "Mastercard", sector: "Payments", assetClass: "Equities" },
  UNH: { name: "UnitedHealth", sector: "Healthcare", assetClass: "Equities" },
  XOM: { name: "Exxon Mobil", sector: "Energy", assetClass: "Equities" },
  LLY: { name: "Eli Lilly", sector: "Pharma", assetClass: "Equities" },
  COIN: { name: "Coinbase Global", sector: "Crypto", assetClass: "Equities" },
  SHOP: { name: "Shopify Inc.", sector: "E-commerce", assetClass: "Equities" },
  SNOW: { name: "Snowflake Inc.", sector: "Cloud Data", assetClass: "Equities" },
  NFLX: { name: "Netflix Inc.", sector: "Entertainment", assetClass: "Equities" },
  CRM: { name: "Salesforce", sector: "Software", assetClass: "Equities" },
  ADBE: { name: "Adobe Inc.", sector: "Software", assetClass: "Equities" },
  CSCO: { name: "Cisco Systems", sector: "Networking", assetClass: "Equities" },
  INTC: { name: "Intel Corp.", sector: "Semiconductors", assetClass: "Equities" },
  QCOM: { name: "Qualcomm Inc.", sector: "Semiconductors", assetClass: "Equities" },
  TXN: { name: "Texas Instruments", sector: "Semiconductors", assetClass: "Equities" },
  IBM: { name: "IBM", sector: "Technology", assetClass: "Equities" },
  ORCL: { name: "Oracle Corp.", sector: "Software", assetClass: "Equities" },
  NOW: { name: "ServiceNow", sector: "Software", assetClass: "Equities" },
  INTU: { name: "Intuit Inc.", sector: "Software", assetClass: "Equities" },
  UBER: { name: "Uber Tech", sector: "Transportation", assetClass: "Equities" },
  ABNB: { name: "Airbnb Inc.", sector: "Travel", assetClass: "Equities" },
  PYPL: { name: "PayPal Holdings", sector: "Payments", assetClass: "Equities" },
  SQ: { name: "Block Inc.", sector: "Payments", assetClass: "Equities" },
  ROKU: { name: "Roku Inc.", sector: "Entertainment", assetClass: "Equities" },
  ZM: { name: "Zoom Video", sector: "Software", assetClass: "Equities" },
  DOCU: { name: "DocuSign", sector: "Software", assetClass: "Equities" },
  CRWD: { name: "CrowdStrike", sector: "Cybersecurity", assetClass: "Equities" },
  DDOG: { name: "Datadog", sector: "Cloud Data", assetClass: "Equities" },
  NET: { name: "Cloudflare", sector: "Cloud Services", assetClass: "Equities" },
  MDB: { name: "MongoDB", sector: "Database", assetClass: "Equities" },
  PANW: { name: "Palo Alto Net", sector: "Cybersecurity", assetClass: "Equities" },
  ZS: { name: "Zscaler", sector: "Cybersecurity", assetClass: "Equities" },
  FTNT: { name: "Fortinet", sector: "Cybersecurity", assetClass: "Equities" },
  OKTA: { name: "Okta Inc.", sector: "Cybersecurity", assetClass: "Equities" },
  TEAM: { name: "Atlassian", sector: "Software", assetClass: "Equities" },
  WDAY: { name: "Workday", sector: "Software", assetClass: "Equities" },
  SPLK: { name: "Splunk Inc.", sector: "Software", assetClass: "Equities" },
  VEEV: { name: "Veeva Systems", sector: "Healthcare", assetClass: "Equities" },
  WMT: { name: "Walmart Inc.", sector: "Retail", assetClass: "Equities" },
  TGT: { name: "Target Corp.", sector: "Retail", assetClass: "Equities" },
  COST: { name: "Costco", sector: "Retail", assetClass: "Equities" },
  HD: { name: "Home Depot", sector: "Retail", assetClass: "Equities" },
  MCD: { name: "McDonald's", sector: "Restaurants", assetClass: "Equities" },
  SBUX: { name: "Starbucks", sector: "Restaurants", assetClass: "Equities" },
  NKE: { name: "NIKE Inc.", sector: "Apparel", assetClass: "Equities" },
  DIS: { name: "Walt Disney", sector: "Entertainment", assetClass: "Equities" },
  CMCSA: { name: "Comcast Corp.", sector: "Entertainment", assetClass: "Equities" },
  PEP: { name: "PepsiCo", sector: "Beverages", assetClass: "Equities" },
  KO: { name: "Coca-Cola", sector: "Beverages", assetClass: "Equities" },
  PG: { name: "Procter & Gamble", sector: "Consumer Goods", assetClass: "Equities" },
  JNJ: { name: "Johnson & Johnson", sector: "Healthcare", assetClass: "Equities" },
  PFE: { name: "Pfizer Inc.", sector: "Pharma", assetClass: "Equities" },
  MRK: { name: "Merck & Co.", sector: "Pharma", assetClass: "Equities" },
  ABBV: { name: "AbbVie Inc.", sector: "Pharma", assetClass: "Equities" },
  TMO: { name: "Thermo Fisher", sector: "Healthcare", assetClass: "Equities" },
  DHR: { name: "Danaher Corp.", sector: "Healthcare", assetClass: "Equities" },
  MDT: { name: "Medtronic", sector: "Healthcare", assetClass: "Equities" },
  SYK: { name: "Stryker Corp.", sector: "Healthcare", assetClass: "Equities" },
  CVX: { name: "Chevron Corp.", sector: "Energy", assetClass: "Equities" },
  COP: { name: "ConocoPhillips", sector: "Energy", assetClass: "Equities" },
  SLB: { name: "Schlumberger", sector: "Energy", assetClass: "Equities" },
  EOG: { name: "EOG Resources", sector: "Energy", assetClass: "Equities" },
  PXD: { name: "Pioneer Natural", sector: "Energy", assetClass: "Equities" },
  OXY: { name: "Occidental Pete", sector: "Energy", assetClass: "Equities" },
  MPC: { name: "Marathon Pete", sector: "Energy", assetClass: "Equities" },
  VLO: { name: "Valero Energy", sector: "Energy", assetClass: "Equities" },
  PSX: { name: "Phillips 66", sector: "Energy", assetClass: "Equities" },
  KMI: { name: "Kinder Morgan", sector: "Energy", assetClass: "Equities" },
  "BTC/USD": { name: "Bitcoin", sector: "Crypto", assetClass: "Crypto" },
  "ETH/USD": { name: "Ethereum", sector: "Crypto", assetClass: "Crypto" },
  "SOL/USD": { name: "Solana", sector: "Crypto", assetClass: "Crypto" },
  "ADA/USD": { name: "Cardano", sector: "Crypto", assetClass: "Crypto" },
  "DOGE/USD": { name: "Dogecoin", sector: "Crypto", assetClass: "Crypto" },
  "DOT/USD": { name: "Polkadot", sector: "Crypto", assetClass: "Crypto" },
  "AVAX/USD": { name: "Avalanche", sector: "Crypto", assetClass: "Crypto" },
  "MATIC/USD": { name: "Polygon", sector: "Crypto", assetClass: "Crypto" },
  "LINK/USD": { name: "Chainlink", sector: "Crypto", assetClass: "Crypto" },
  "UNI/USD": { name: "Uniswap", sector: "Crypto", assetClass: "Crypto" },
  SPY: { name: "S&P 500 ETF", sector: "Index", assetClass: "ETFs" },
  QQQ: { name: "Invesco QQQ", sector: "Index", assetClass: "ETFs" },
  GLD: { name: "SPDR Gold Trust", sector: "Commodity", assetClass: "Commodities" },
  TLT: { name: "20+ Year Treasury", sector: "Bonds", assetClass: "Bonds" },
  IWM: { name: "iShares Russell 2000", sector: "Index", assetClass: "ETFs" },
  DIA: { name: "SPDR Dow Jones", sector: "Index", assetClass: "Indices" },
  VTI: { name: "Vanguard Total Stock", sector: "Index", assetClass: "ETFs" },
  VOO: { name: "Vanguard S&P 500", sector: "Index", assetClass: "Indices" },
  ARKK: { name: "ARK Innovation", sector: "Innovation", assetClass: "ETFs" },
  SMH: { name: "VanEck Semiconductor", sector: "Semiconductors", assetClass: "ETFs" },
};
