/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PopoutRouteImport } from './routes/popout'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWatchlistsRouteImport } from './routes/_app/watchlists'
import { Route as AppSocialRouteImport } from './routes/_app/social'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSentimentRouteImport } from './routes/_app/sentiment'
import { Route as AppScreenersRouteImport } from './routes/_app/screeners'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPredictionsRouteImport } from './routes/_app/predictions'
import { Route as AppPortfolioRouteImport } from './routes/_app/portfolio'
import { Route as AppOrderbookRouteImport } from './routes/_app/orderbook'
import { Route as AppOptionsRouteImport } from './routes/_app/options'
import { Route as AppNewsRouteImport } from './routes/_app/news'
import { Route as AppMlLabRouteImport } from './routes/_app/ml-lab'
import { Route as AppMarketsRouteImport } from './routes/_app/markets'
import { Route as AppMacroRouteImport } from './routes/_app/macro'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppKnowledgeGraphRouteImport } from './routes/_app/knowledge-graph'
import { Route as AppInsidersRouteImport } from './routes/_app/insiders'
import { Route as AppGuildsRouteImport } from './routes/_app/guilds'
import { Route as AppFilingsRouteImport } from './routes/_app/filings'
import { Route as AppExecutionLabRouteImport } from './routes/_app/execution-lab'
import { Route as AppEarningsRouteImport } from './routes/_app/earnings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCopyTradingRouteImport } from './routes/_app/copy-trading'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppAiResearchRouteImport } from './routes/_app/ai-research'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'

const PopoutRoute = PopoutRouteImport.update({
  id: '/popout',
  path: '/popout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchlistsRoute = AppWatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSentimentRoute = AppSentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenersRoute = AppScreenersRouteImport.update({
  id: '/screeners',
  path: '/screeners',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsRoute = AppPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderbookRoute = AppOrderbookRouteImport.update({
  id: '/orderbook',
  path: '/orderbook',
  getParentRoute: () => AppRoute,
} as any)
const AppOptionsRoute = AppOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppMlLabRoute = AppMlLabRouteImport.update({
  id: '/ml-lab',
  path: '/ml-lab',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppMacroRoute = AppMacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeGraphRoute = AppKnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => AppRoute,
} as any)
const AppInsidersRoute = AppInsidersRouteImport.update({
  id: '/insiders',
  path: '/insiders',
  getParentRoute: () => AppRoute,
} as any)
const AppGuildsRoute = AppGuildsRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => AppRoute,
} as any)
const AppFilingsRoute = AppFilingsRouteImport.update({
  id: '/filings',
  path: '/filings',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutionLabRoute = AppExecutionLabRouteImport.update({
  id: '/execution-lab',
  path: '/execution-lab',
  getParentRoute: () => AppRoute,
} as any)
const AppEarningsRoute = AppEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCopyTradingRoute = AppCopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiResearchRoute = AppAiResearchRouteImport.update({
  id: '/ai-research',
  path: '/ai-research',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/popout': typeof PopoutRoute
  '/agents': typeof AppAgentsRoute
  '/ai-research': typeof AppAiResearchRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/copy-trading': typeof AppCopyTradingRoute
  '/dashboard': typeof AppDashboardRoute
  '/earnings': typeof AppEarningsRoute
  '/execution-lab': typeof AppExecutionLabRoute
  '/filings': typeof AppFilingsRoute
  '/guilds': typeof AppGuildsRoute
  '/insiders': typeof AppInsidersRoute
  '/knowledge-graph': typeof AppKnowledgeGraphRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/macro': typeof AppMacroRoute
  '/markets': typeof AppMarketsRoute
  '/ml-lab': typeof AppMlLabRoute
  '/news': typeof AppNewsRoute
  '/options': typeof AppOptionsRoute
  '/orderbook': typeof AppOrderbookRoute
  '/portfolio': typeof AppPortfolioRoute
  '/predictions': typeof AppPredictionsRoute
  '/profile': typeof AppProfileRoute
  '/screeners': typeof AppScreenersRoute
  '/sentiment': typeof AppSentimentRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/watchlists': typeof AppWatchlistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/popout': typeof PopoutRoute
  '/agents': typeof AppAgentsRoute
  '/ai-research': typeof AppAiResearchRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/copy-trading': typeof AppCopyTradingRoute
  '/dashboard': typeof AppDashboardRoute
  '/earnings': typeof AppEarningsRoute
  '/execution-lab': typeof AppExecutionLabRoute
  '/filings': typeof AppFilingsRoute
  '/guilds': typeof AppGuildsRoute
  '/insiders': typeof AppInsidersRoute
  '/knowledge-graph': typeof AppKnowledgeGraphRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/macro': typeof AppMacroRoute
  '/markets': typeof AppMarketsRoute
  '/ml-lab': typeof AppMlLabRoute
  '/news': typeof AppNewsRoute
  '/options': typeof AppOptionsRoute
  '/orderbook': typeof AppOrderbookRoute
  '/portfolio': typeof AppPortfolioRoute
  '/predictions': typeof AppPredictionsRoute
  '/profile': typeof AppProfileRoute
  '/screeners': typeof AppScreenersRoute
  '/sentiment': typeof AppSentimentRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/watchlists': typeof AppWatchlistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/popout': typeof PopoutRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/ai-research': typeof AppAiResearchRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/copy-trading': typeof AppCopyTradingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/earnings': typeof AppEarningsRoute
  '/_app/execution-lab': typeof AppExecutionLabRoute
  '/_app/filings': typeof AppFilingsRoute
  '/_app/guilds': typeof AppGuildsRoute
  '/_app/insiders': typeof AppInsidersRoute
  '/_app/knowledge-graph': typeof AppKnowledgeGraphRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/macro': typeof AppMacroRoute
  '/_app/markets': typeof AppMarketsRoute
  '/_app/ml-lab': typeof AppMlLabRoute
  '/_app/news': typeof AppNewsRoute
  '/_app/options': typeof AppOptionsRoute
  '/_app/orderbook': typeof AppOrderbookRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/predictions': typeof AppPredictionsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/screeners': typeof AppScreenersRoute
  '/_app/sentiment': typeof AppSentimentRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/watchlists': typeof AppWatchlistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/popout'
    | '/agents'
    | '/ai-research'
    | '/alerts'
    | '/analytics'
    | '/copy-trading'
    | '/dashboard'
    | '/earnings'
    | '/execution-lab'
    | '/filings'
    | '/guilds'
    | '/insiders'
    | '/knowledge-graph'
    | '/leaderboard'
    | '/macro'
    | '/markets'
    | '/ml-lab'
    | '/news'
    | '/options'
    | '/orderbook'
    | '/portfolio'
    | '/predictions'
    | '/profile'
    | '/screeners'
    | '/sentiment'
    | '/settings'
    | '/social'
    | '/watchlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/popout'
    | '/agents'
    | '/ai-research'
    | '/alerts'
    | '/analytics'
    | '/copy-trading'
    | '/dashboard'
    | '/earnings'
    | '/execution-lab'
    | '/filings'
    | '/guilds'
    | '/insiders'
    | '/knowledge-graph'
    | '/leaderboard'
    | '/macro'
    | '/markets'
    | '/ml-lab'
    | '/news'
    | '/options'
    | '/orderbook'
    | '/portfolio'
    | '/predictions'
    | '/profile'
    | '/screeners'
    | '/sentiment'
    | '/settings'
    | '/social'
    | '/watchlists'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/popout'
    | '/_app/agents'
    | '/_app/ai-research'
    | '/_app/alerts'
    | '/_app/analytics'
    | '/_app/copy-trading'
    | '/_app/dashboard'
    | '/_app/earnings'
    | '/_app/execution-lab'
    | '/_app/filings'
    | '/_app/guilds'
    | '/_app/insiders'
    | '/_app/knowledge-graph'
    | '/_app/leaderboard'
    | '/_app/macro'
    | '/_app/markets'
    | '/_app/ml-lab'
    | '/_app/news'
    | '/_app/options'
    | '/_app/orderbook'
    | '/_app/portfolio'
    | '/_app/predictions'
    | '/_app/profile'
    | '/_app/screeners'
    | '/_app/sentiment'
    | '/_app/settings'
    | '/_app/social'
    | '/_app/watchlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PopoutRoute: typeof PopoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/popout': {
      id: '/popout'
      path: '/popout'
      fullPath: '/popout'
      preLoaderRoute: typeof PopoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watchlists': {
      id: '/_app/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof AppWatchlistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sentiment': {
      id: '/_app/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof AppSentimentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screeners': {
      id: '/_app/screeners'
      path: '/screeners'
      fullPath: '/screeners'
      preLoaderRoute: typeof AppScreenersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predictions': {
      id: '/_app/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AppPredictionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orderbook': {
      id: '/_app/orderbook'
      path: '/orderbook'
      fullPath: '/orderbook'
      preLoaderRoute: typeof AppOrderbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/options': {
      id: '/_app/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof AppOptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ml-lab': {
      id: '/_app/ml-lab'
      path: '/ml-lab'
      fullPath: '/ml-lab'
      preLoaderRoute: typeof AppMlLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets': {
      id: '/_app/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/macro': {
      id: '/_app/macro'
      path: '/macro'
      fullPath: '/macro'
      preLoaderRoute: typeof AppMacroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-graph': {
      id: '/_app/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof AppKnowledgeGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insiders': {
      id: '/_app/insiders'
      path: '/insiders'
      fullPath: '/insiders'
      preLoaderRoute: typeof AppInsidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guilds': {
      id: '/_app/guilds'
      path: '/guilds'
      fullPath: '/guilds'
      preLoaderRoute: typeof AppGuildsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/filings': {
      id: '/_app/filings'
      path: '/filings'
      fullPath: '/filings'
      preLoaderRoute: typeof AppFilingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/execution-lab': {
      id: '/_app/execution-lab'
      path: '/execution-lab'
      fullPath: '/execution-lab'
      preLoaderRoute: typeof AppExecutionLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/earnings': {
      id: '/_app/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AppEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copy-trading': {
      id: '/_app/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof AppCopyTradingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-research': {
      id: '/_app/ai-research'
      path: '/ai-research'
      fullPath: '/ai-research'
      preLoaderRoute: typeof AppAiResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppAiResearchRoute: typeof AppAiResearchRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCopyTradingRoute: typeof AppCopyTradingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEarningsRoute: typeof AppEarningsRoute
  AppExecutionLabRoute: typeof AppExecutionLabRoute
  AppFilingsRoute: typeof AppFilingsRoute
  AppGuildsRoute: typeof AppGuildsRoute
  AppInsidersRoute: typeof AppInsidersRoute
  AppKnowledgeGraphRoute: typeof AppKnowledgeGraphRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMacroRoute: typeof AppMacroRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppMlLabRoute: typeof AppMlLabRoute
  AppNewsRoute: typeof AppNewsRoute
  AppOptionsRoute: typeof AppOptionsRoute
  AppOrderbookRoute: typeof AppOrderbookRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppPredictionsRoute: typeof AppPredictionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScreenersRoute: typeof AppScreenersRoute
  AppSentimentRoute: typeof AppSentimentRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppWatchlistsRoute: typeof AppWatchlistsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppAiResearchRoute: AppAiResearchRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCopyTradingRoute: AppCopyTradingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEarningsRoute: AppEarningsRoute,
  AppExecutionLabRoute: AppExecutionLabRoute,
  AppFilingsRoute: AppFilingsRoute,
  AppGuildsRoute: AppGuildsRoute,
  AppInsidersRoute: AppInsidersRoute,
  AppKnowledgeGraphRoute: AppKnowledgeGraphRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMacroRoute: AppMacroRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppMlLabRoute: AppMlLabRoute,
  AppNewsRoute: AppNewsRoute,
  AppOptionsRoute: AppOptionsRoute,
  AppOrderbookRoute: AppOrderbookRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppPredictionsRoute: AppPredictionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppScreenersRoute: AppScreenersRoute,
  AppSentimentRoute: AppSentimentRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppWatchlistsRoute: AppWatchlistsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PopoutRoute: PopoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
